---
title: "TrumpTwitter"
author: "Anup Adhikari"
date: "4/10/2020"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

#packgaes
```{r,warning=FALSE,echo=FALSE}
library(tidytext)
library(dplyr)
library(tm)
library(wordcloud2)
library(scales)
library(reshape2)
library(syuzhet)
library(RColorBrewer)
library(stylo)
```

# Read the file
```{r,warning=FALSE,echo=FALSE}
trump <- read.csv(file.choose(), header = T,fileEncoding = "utf-8")
trumptweets <- trump$text
str(trump)
```

# Building corpus
```{r}
corp <- iconv(trump$text)
corp <- Corpus(VectorSource(corp))
corp <- tm_map(corp,tolower)
corp <- tm_map(corp,removePunctuation)
corp <- tm_map(corp,removeNumbers)
removeURL <- function(x) gsub("https[[:alnum:]]*","", x)
removeEmail<-function(x) gsub("\\b[A-Z a-z 0-9._ - ]*[@](.*?)[...]{1,3} \\b", "", x)
removeTwittertag <- function(x) gsub("RT |via", "", x)
removeUsername <- function(x) gsub("[@][a - zA - Z0 - 9_]{1,15}", "", x)
```


# Cleanin data
```{r}
cleandata <- tm_map(corp,removeWords, stopwords("english"))
cleandata <- tm_map(cleandata,stripWhitespace)
cleandata <- tm_map(cleandata,content_transformer(removeURL))
cleandata <- tm_map (cleandata, content_transformer(removeEmail))
cleandata <- tm_map (cleandata, content_transformer(removeTwittertag))
cleandata <- tm_map(cleandata,content_transformer(removeUsername))
inspect(corp[1:5])
```
# Term Documented Matrix
```{r}
tdm <- TermDocumentMatrix(cleandata)
tdm
tdm <- as.matrix(tdm)
tdm[1:10,1:20]
```


#cluster Analysis of Tweets
```{r, warning= FALSE}
tdm1 <- TermDocumentMatrix(corp, control = list(minWordLength = c( 1, Inf)))
tdm1
tdm2 <- removeSparseTerms(tdm1, sparse = 0.98)
tdm2
m <- as.matrix(tdm2) 
freq <- rowSums(m)
freq <- subset(freq, freq >=50)
barplot(freq, las=2,col=rainbow(50))
```


```{r}
distance <- dist(scale(m))
print(distance,digits = 2)
hc <- hclust(distance,method = "ward.D")
plot(hc,hang=-1)
rect.hclust(hc,k=10) #10 clusters
```

```{r}
w <- rowSums(tdm)
w <- subset(w,w>=25)
barplot(w,
        las=2,
        col=rainbow(50))
```

```{r, warning=FALSE}
w <- sort(rowSums(tdm),decreasing = TRUE)
set.seed(111)
wordcloud(words = names(w),
          freq = w,
          max.words = 150,
          random.order = FALSE,
          min.freq = 5,
          colors = brewer.pal(12,'Set1'),
          sacle=c(50,0.3),rot.per = 0.7)
```

```{r, warning=FALSE}
trumptweets <- iconv(trump$text, to ="utf-8")
s <- get_nrc_sentiment(trumptweets)
get_nrc_sentiment('delay')
barplot(colSums(s),labs=2,
        col=rainbow(11))
```




